env:
  browser: true
  es2021: true
extends: eslint:recommended
overrides: []
parserOptions:
  ecmaVersion: latest
rules: {
        "indent" : "off",
        "no-unused-vars": "off",
        "import/no-dynamic-require" : "off",
        "global-require": "off",
        "no-undef": "off",
}
